Models/Meetinginfo.cs
namespace MeetingApp.Models{

public class MeetingInfo{


    public int Id {get; set;}

    public string? Location { get; set; }

    public DateTime Date { get; set; }
    public int NumberOfPeople { get; set; }
}



}

Models/Repository.cs
namespace MeetingApp.Models
{
    public class Repository
    {

        public static List<UserInfo> _users = new();

        static Repository()
        {
            _users.Add(new UserInfo() {Id=1,Name="Ali", Email="abc@gmail.com", Phone="11",WillAttend=true});
            _users.Add(new UserInfo() {Id=2,Name="Ali", Email="abc@gmail.com", Phone="11",WillAttend=true});
            _users.Add(new UserInfo() {Id=3,Name="Ali", Email="abc@gmail.com", Phone="11",WillAttend=true});
        }
        public static List<UserInfo> Users
        {
            get
            {
                return _users;
            }
        }

        public static void CreateUser(UserInfo user)
        {
            user.Id=Users.Count + 1;
            _users.Add(user);
        }

        public static UserInfo? GetById(int id){
            return _users.FirstOrDefault(user=> user.Id == id);
        }
    }
}

Models/UserInfo.cs
using System.ComponentModel.DataAnnotations;

namespace MeetingApp.Models{

    public class UserInfo{
        public int Id { get; set; }
        [Required(ErrorMessage ="Ad Zorunlu")]
        public  string? Name { get; set; }
        [Required(ErrorMessage ="Telefon Zorunlu")]
        public string? Phone { get; set; }
        [Required]
        [EmailAddress(ErrorMessage ="Email Zorunlu")]
        public string? Email { get; set; }
        [Required(ErrorMessage ="Katılım Durum Zorunlu")]
        public bool? WillAttend { get; set; }

    }
}

Controllers/HomeController.cs
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers
{
    public class HomeController: Controller {

        //localhost/home/index 
        public IActionResult Index()
        {
            int saat = DateTime.Now.Hour; 

            ViewBag.selamlama = saat > 12? "İyi Günler":"Günaydın";
            ViewBag.Username = "Ugurcan";

            var meetingInfo= new MeetingInfo(){
                Id=1,
                Location="Istanbul",
                Date= new DateTime(2024,01,20,20,0,0),
                NumberOfPeople=100
            };


            return View(meetingInfo);
        }
    }
}

Controllers/MeetingController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace MeetingApp.Controllers
{

    public class MeetingController : Controller
    {

        [HttpGet]
        public IActionResult Apply()
        {
            return View();
        }

        [HttpPost]

        public IActionResult Apply(UserInfo model)
        {
            if (ModelState.IsValid)
            {

                Repository.CreateUser(model);
                ViewBag.UserCount = Repository.Users.Where(i => i.WillAttend == true).Count();
                return View("Thanks", model);
            }else{
                return View(model);
            }
        }

        public IActionResult List()
        {
            return View(Repository.Users);
        }

        public IActionResult Details(int id)
        {
            return View(Repository.GetById(id));
        }
    }
}

Views/Home/index.cshtml
@model MeetingInfo
@{
    ViewBag.Title = "Başvuru Bilgisi";
    Layout = "_Layout2";
}
<main class="text-center"> 
    <h1 class="h4">@ViewBag.selamlama,@ViewBag.Username</h1>
    <p>Toplantı Katılım Durumunuzu Belirtin</p>

    <div class="card my-2">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">@Model.Location</li>
            <li class="list-group-item">@Model.Date.ToString("dd/MM/yyyy HH:mm:ss") tarihinde gerçekleşecek</li>
            <li class="list-group-item">@Model.NumberOfPeople Kişilik Kontenjan</li>
        </ul>
    </div>
    <a class="btn btn-sm btn-outline-primary" asp-controller="Meeting" asp-action="Apply">Başvuru yap</a>
</main>

Views/Meeting/Apply.cshtml
@model UserInfo

@{
    ViewBag.Title = "Başvuru Formu";
}
<h1 class="h4 text-center">Toplantı Katılım Formu</h1>
<form method="post" action="/Meeting/Apply">
<div asp-validation-summary="All"></div>
    <div class="mb-3">
        <label asp-for="Name" class="form-label">Name</label>
        <input asp-for="Name" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Phone" class="form-label">Phone</label>
        <input asp-for="Phone" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Email" class="form-label">Email</label>
        <input asp-for="Email" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="WillAttend" class="form-label">Katılım Durumu</label>
        <select asp-for="WillAttend" class="form-select">
            <option value="">Seçiniz</option>
            <option value="true">Evet</option>
            <option value="false">Hayır</option>
        </select>

    </div>
    <button class="btn btn-primary" type="submit">Kaydet</button>
</form>

Views/Meeting/Details.cshtml
@model UserInfo
@{
    ViewBag.Title="Başvuru Detayı";
}
<main class="text-center">
    <h1 class="h4">Başvuru Detayı</h1>
    <p>İsim:@Model.Name</p>
    <p>Email:@Model.Email</p>
    <p>Telefon:@Model.Phone</p>
</main>

Views/Meeting/List.cshtml
@model List<UserInfo>

@{
    ViewBag.Title = "Toplantı Katılım Listesi Özeti";
}

<main class="text-center">

    <h1 class="h4">Toplantı Katılım Listesi</h1>
    <table class="table table-bordered">
        <thead>
            <tr>
                <td>Ad</td>
                <td>Katılım Durum</td>
                <td></td>
            </tr>
        </thead>
        <tbody>

            @{int i=0;}

            @foreach (var user in Model)
            {
                var durum= user.WillAttend == true ? "Evet":"Hayır";
                var classname = user.WillAttend == true ? "table-success":"table-danger";

                if(user.WillAttend == true){
                    i++;
                }

                <tr class="@classname">
                    <td>@user.Name</td>
                    <td>@durum</td>
                    <td>
                        <a class="btn btn-sm btn-primary" href="/meeting/details/@user.Id">Detay</a>
                    </td>
                </tr>

            }
        </tbody>
    </table>
    <div class="card">
        <div class="card-body">
            <p>Katılımcı sayısı: @i</p>
        </div>
    </div>
</main>

Views/Meeting/Thanks.cshtml
@model UserInfo
@{
    ViewBag.Title = "Başvuru Durumu";
}
<main class="text-center">
    <h1 class="h4">Başvuru Durumu</h1>

    @if(Model.WillAttend == true)
    {
        <p>@Model.Name Toplantıya @ViewBag.UserCount kişi katılıyor</p>
        <a class="btn btn-sm btn-outline-primary" href="/meeting/list">Toplantı Katılımcı Listesi</a>
    } else {

        <p>@Model.Name,katılmadığından dolayı üzgünüz.</p>
        <a class="btn btn-sm btn-outline-primary" href="/meeting/apply">Başvuru Formu</a>
    }


</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css" />
    <title>@ViewBag.Title - MeetingApp</title>
</head>

<body>
    <div class="bg-primary text-white p-2 text-center">
        MeetingApp
    </div>
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto ">
                <div class="card">
                    <div class="card-body">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css"/>
    <title>Document</title>
</head>
<body>
    <div class="bg-success text-white p-2 text-center">
        MeetingApp
    </div>
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto text-center">
                <div class="card">
                    <div class="card-body">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</body>
</html>